Add sytrf
libmir/mir-lapack pull request #2
Opened 2018-02-05 15:40 UTC by 080993

Method for LDL factorization.

2018-02-05 15:45 UTC, 9il requested changes

2018-02-05 15:45 UTC, 9il commented on source/mir/lapack.d
> +	char uplo = 'L';
Должно быть две версии со  `stairs`, как для `spev`. Также нужно по одному небольшому тесту добавить

2018-02-06 12:02 UTC, 9il commented
Тесты

2018-02-14 04:15 UTC, 9il requested changes

2018-02-14 04:15 UTC, 9il commented on source/mir/lapack.d
> +    lapackint ldb = max(1, n);
Это не верно.

2018-02-14 04:15 UTC, 9il commented on source/mir/lapack.d
> +    lapackint ldb = max(1, n);
Страйды используйте

2018-02-14 13:56 UTC, 9il commented on source/mir/lapack.d
> +public import cblas: Uplo;
Давайте пока без Uplo, а просто с `char` , чтобы не делать дополнительную зависимость от blas

2018-02-15 09:09 UTC, 9il requested changes
Почему info == 0? А *_wq функции для новичков х не нужны? Если не нужны, то нужно написать в комментариях какая у  work длина. Если нужны, то слелать

2018-02-17 08:26 UTC, 9il requested changes

2018-02-17 08:26 UTC, 9il commented on source/mir/lapack.d
> +    assert(a == a.transposed, "matrix must be symmetric");
Эту проверку нельзя делать. Матрица может быть нескметиричной, к примеру после symm, но использовать её будут как симметричную. Иначе Uplo был бы не нужен.

Кстате для Uplo мы же поменяли на chair для lapack, чтобы не добавлять зависимость о Blas

2018-02-17 08:26 UTC, 9il commented on source/mir/lapack.d
> +    Uplo uplo
В mir lapack же нет Uplo. Договаривались делать char

2018-02-17 08:26 UTC, 9il commented on source/mir/lapack.d
> +    assert(a == a.transposed, "matrix must be symmetric");
Она может не быть симметричной в реальности. Лапак это не требует

2018-02-19 02:19 UTC, 9il commented
1. potrf удаляйте, его уже добавили в https://github.com/libmir/mir-lapack/pull/4 очередной раз проверять
2. про ld? я Вам писал. Третий раз писать ну буду
3. С_UPLO не нужен, он должен передаваться какой есть. Вся логика в лубек. Это просто врапперы.

2018-02-25 07:06 UTC, thewilsonator commented on source/mir/lapack.d
> +    assert(a.length!0 == a.length!1, "mutrix must be squared");
Typo mutrix -> matrix.
Also `squared` should be `square` (in all the messages), make the message an private enum since they are all the same.

2018-02-25 07:07 UTC, thewilsonator commented
The binary files should be removed.

2018-02-28 14:23 UTC, merged